services:
  rustdesk_api:
    container_name: rustdesk_api
    image: swr.cn-north-4.myhuaweicloud.com/yufeng-yf/rustdesk_api:latest
    restart: unless-stopped
    ports:
      - "21114:21114"
    environment:
      - DATABASE=sqlite3
      - TZ=Asia/Shanghai
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

