include:
  - ./docker-compose-network.yml

services:
  mysql:
    image: mysql:8.4.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD='mysql_xSHa67'
      - MYSQL_DATABASE=rustdesk_api
      - MYSQL_USER=rustdesk_api
      - MYSQL_PASSWORD='mysql_xSHa67'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - rustdesk_api_network
